[package]
name = "obscura-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonrpsee = { version = "0.23", features = ["server"] }
serde = { version = "1.0", features = ["derive"] }
obscura-core = { path = "../core" }
tower = { version = "0.4", features = ["util"] }
