[package]
name = "obscura-zk"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-std = "0.4"
ark-relations = "0.4"
ark-groth16 = "0.4"
ark-bn254 = "0.4"
serde = { version = "1.0", features = ["derive"] }
obscura-core = { path = "../core" }
