name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Cache cargo registry + build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run rustfmt check
        run: cargo fmt --all -- --check

      - name: Run clippy
        env:
          RUSTFLAGS: "-D warnings"
        run: cargo clippy --workspace --all-targets --all-features

      - name: Run tests
        run: cargo test --workspace --all-features --verbose

      - name: Build docs
        run: cargo doc --no-deps --workspace
